### ISSUE TITLE
Rounding options for more than just forecast

### ISSUE THREAD

**Issue by Dhtjf** [mlamberts78/weather-chart-card#101]
First, this is an absolutely awesome card, so thank you.

**Is your feature request related to a problem? Please describe.**
When inputting my local sensors from my Tempest weather station (built in integration) for the current condition entities, I'm getting all available digits. It does not matter if I change the precision shown on the entity.

For example, see current temperature, feels like, and pressure:
![image](https://github.com/mlamberts78/weather-chart-card/assets/59745069/8260f387-6016-4d45-98f1-13c85277a66e)

Versus the precision settings, for example, feels like:
![image](https://github.com/mlamberts78/weather-chart-card/assets/59745069/b030c9e0-dc58-4cd3-82ca-0ae73cd99011)

My card yaml:
```
type: custom:weather-chart-card
entity: weather.forecast_xxxxxx
show_main: true
show_temperature: true
show_current_condition: true
show_attributes: true
show_time: false
show_day: false
show_date: false
show_humidity: true
show_pressure: true
show_wind_direction: true
show_wind_speed: true
show_sun: true
show_feels_like: true
icons_size: 25
animated_icons: false
icon_style: style1
forecast:
  precipitation_type: rainfall
  labels_font_size: '11'
  precip_bar_size: '100'
  style: style2
  show_wind_forecast: true
  condition_icons: true
  round_temp: false
  type: daily
  use_12hour_format: false
units:
  pressure: ''
  speed: ''
temp: sensor.st_00123271_temperature
feels_like: sensor.st_00123271_feels_like
press: sensor.st_00123271_air_pressure
humid: sensor.st_00123271_humidity
uv: sensor.st_00123271_uv_index
winddir: sensor.st_00123271_wind_direction_average
windspeed: sensor.st_00123271_wind_speed_average
```

**Describe the solution you'd like**
Ability to either set precision directly in the card or utilize the precision set within the entity settings. The card did not appear to accept a template entry. Of course, a workaround is to make a helper of each entity with a template that performs the rounding.
