### ISSUE TITLE
Weather chart behind a conditional card is empty when revealed on condition true

### ISSUE THREAD

**Issue by wigster** [mlamberts78/weather-chart-card#103]
**Describe the bug**
I have a weather chart card embedded in a conditional card. I have this twice and an input_select in the dashboard switches between the visibility of these cards. When the weather chart card is revealed, it is empty until the browser is refreshed with F5 (see screenshot). Result is the same with both iOS and Edge on Windows.

When the nput_select is switched back to the original setting, the orginal card reappears, but it is now empty too, until a refresh.

**Expected behavior**
The card should be refreshed when it appears in the dashboard.

**Screenshots**

![image](https://github.com/mlamberts78/weather-chart-card/assets/10956987/808683da-5053-42f3-88d9-27db3ae341d9)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION :2.3.0
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2024.2.2
 - OS: HAOS latest
 - Browser Edge Windows 123. Safari iOS 17.4

**Additional context**
Here is the config for the card:
```yaml
type: conditional
conditions:
  - condition: state
    entity: input_select.wu_source
    state_not: other
card:
  type: custom:weather-chart-card
  entity: weather.wu_prague
  show_time: false
  show_date: true
  forecast:
    precipitation_type: ''
    type: daily
    style: style2
    round_temp: false
    use_12hour_format: false
  units:
    pressure: ''
    speed: ''
  show_current_condition: true
  show_temperature: true
  animated_icons: true
  icon_style: style1
  show_main: true
  show_attributes: false
  icons_size: '50'
  current_temp_size: '20'
  title: Prognoza Praga
```
