### ISSUE TITLE
Uncaught WebKit errors

### ISSUE THREAD

**Issue by erkr** [mlamberts78/weather-chart-card#104]
**Describe the bug**
Since my update to v2.3.0, I noticed intermittently some uncaught webkit errors in my log, originating from this card:
``` yaml
Logger: frontend.js.latest.202402071
Source: components/system_log/__init__.py:306
First occurred: 12:15:59 (4 occurrences)
Last logged: 12:18:11

Uncaught error from WebKit 605.1.15 on iOS 17.3.1 TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector') measureCard (/hacsfiles/weather-chart-card/weather-chart-card.js:17934:33) /hacsfiles/weather-chart-card/weather-chart-card.js:17774:23
``` 

**To Reproduce**
I just opened the view with the card. Sadly it happens only intermittently. I hope the log contains enough info to spot the root cause.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 2.3.0
 - HOME ASSISTANT VERSION: 2024.2.1
 - INSTALLATION TYPE: HassOS
 - OS: 11.5
 - Browser: companion app iOS

**Additional context**
