### ISSUE TITLE
Would love the chart labels to be CSS-able

### ISSUE THREAD

**Issue by daj102** [mlamberts78/weather-chart-card#118]
**Is your feature request related to a problem? Please describe.**
I just discovered this extension and it looks great :)  I use it on a large TV display and I use the 'amoled' style, along with card-mod to change fonts and things.  However, on the black background, the day labels are very nearly impossible to read.  I saw that you had examples of a dark theme on the git README, but I'm guessing they use a specific CSS variable or something?  Inspecting the DOM, I can see that the table is on a canvas, but I can't see the style on the day label.  Also, the vertical column separators is really dark too.

**Describe the solution you'd like**
The best solution would be to have parameters in the configuration to specify the font/color/size of those labels.  However, either a description of how to change the colors of the table labels, a CSS style list, or the addition of CSS styles when you generate the table ... would also be fine.

**Additional context**
Here is a screenshot of your card below another weather card that I'm looking at.  The style of the view is set to amoled:

![image](https://github.com/mlamberts78/weather-chart-card/assets/5316459/f6a1c387-19a1-466d-9307-8d7c9976687a)

**Comment by mlamberts78** [comment]
Please check the readme for the forecast options: chart_datetime_color & chart_text_color

**Comment by daj102** [comment]
Ah ... doh.  Obviously didn't read carefully enough ...

However, it doesn't seem to work; I've tried with hex RGB values and color names, but it doesn't seem to stick:

```yaml
type: custom:weather-chart-card
entity: weather.home
show_main: true
show_temperature: true
show_current_condition: true
show_attributes: true
show_time: false
show_time_seconds: false
show_day: false
show_date: false
show_humidity: false
show_pressure: false
show_wind_direction: false
show_wind_speed: true
show_sun: false
show_feels_like: true
icons_size: 25
animated_icons: true
icon_style: style1
forecast:
  precipitation_type: rainfall
  labels_font_size: '12'
  precip_bar_size: '80'
  style: style2
  show_wind_forecast: true
  condition_icons: true
  round_temp: false
  type: daily
  number_of_forecasts: '0'
current_temp_size: '38'
units:
  pressure: ''
  speed: ''
use_12hour_format: false
chart_text_color: blue
chart_datetime_color: blue
```

![image](https://github.com/mlamberts78/weather-chart-card/assets/5316459/1990d5c8-f7c4-4a13-8f9e-029a300a9549)

(btw - thanks for the speedy response; really appreciate it)
