### ISSUE TITLE
Add ability to show day/date at 00:00 in the forecast

### ISSUE THREAD

**Issue by gcoan** [mlamberts78/weather-chart-card#131]
**Is your feature request related to a problem? Please describe.**
The current forecast is easy to read, I am using it with the UK Met Office 3 hourly forecast, but as this gives the forecast for several days ahead I would like the option for future days to be annotated eg. Tue 5 Mar above the 00:00 time

**Describe the solution you'd like**
As above

**Additional context**
Current setup:
```yaml
          - type: custom:weather-chart-card
            entity: weather.met_office_daily
            show_main: true
            show_temperature: true
            show_current_condition: false
            show_attributes: true
            show_time: false
            show_humidity: true
            show_pressure: false
            show_wind_direction: false
            show_wind_speed: false
            show_sun: false
            show_feels_like: false
            use_12hour_format: false
            icons_size: 25
            animated_icons: true
            icon_style: style1
            forecast:
              show_probability: true
              labels_font_size: '11'
              precip_bar_size: '100'
              style: style1
              show_wind_forecast: true
              condition_icons: true
              round_temp: false
              type: hourly
            units:
              pressure: ''
              speed: ''
            show_time_seconds: false
```           

Add date/time here similar to the other weather card (that I’d like to replace):
![IMG_0685](https://github.com/mlamberts78/weather-chart-card/assets/142018870/519bada1-819d-4361-9076-9db1554f1557)

By the way ‘show_humidity’ setting in the yaml is described as ‘show_humid’ in the read.me doc
