### ISSUE TITLE
Daily forecast shows hours not name of day

### ISSUE THREAD

**Issue by MB7i** [mlamberts78/weather-chart-card#137]
Daily chart shows 12:00 instead of the expected weekdays i.e. Mon, Tue, Wed, ...
Screenshot below shows a daily forecast for reference with the expected hourly format.

 - WEATHER-CHART-CARD VERSION 2.4.2
 - HOME ASSISTANT VERSION 2024.2.5

![image](https://github.com/mlamberts78/weather-chart-card/assets/157990612/8224ba7f-159b-47d0-a67c-43b0a06aaa23)

```
type: vertical-stack
cards:
  - type: custom:weather-chart-card
    entity: weather.forecast_home
    show_main: true
    show_temperature: true
    show_current_condition: true
    show_attributes: true
    show_time: false
    show_day: true
    show_date: true
    show_humidity: true
    show_pressure: false
    show_wind_direction: true
    show_wind_speed: true
    show_sun: true
    show_feels_like: false
    use_12hour_format: false
    icons_size: 25
    animated_icons: true
    icon_style: style1
    forecast:
      precipitation_type: rainfall
      labels_font_size: '11'
      precip_bar_size: '100'
      style: style2
      show_wind_forecast: true
      condition_icons: true
      round_temp: false
      type: daily
    units:
      pressure: ''
      speed: ''
  - type: custom:weather-chart-card
    entity: weather.forecast_home
    show_main: false
    show_temperature: true
    show_current_condition: true
    show_attributes: true
    show_time: false
    show_day: true
    show_date: true
    show_humidity: false
    show_pressure: false
    show_wind_direction: false
    show_wind_speed: false
    show_sun: false
    show_feels_like: false
    use_12hour_format: false
    icons_size: 25
    animated_icons: true
    icon_style: style1
    forecast:
      precipitation_type: probability
      labels_font_size: '11'
      precip_bar_size: '100'
      style: style2
      show_wind_forecast: true
      condition_icons: true
      round_temp: false
      type: hourly
    units:
      pressure: ''
      speed: ''
```
