### ISSUE TITLE
Daily forecast day name showing as 7:00 am

### ISSUE THREAD

**Issue by wigster** [mlamberts78/weather-chart-card#150]
**Describe the bug**
This used to be ok, but something change and now my the name of the day in the daily forecast is showing as 7:00, which is the beginning of the day for the weather integration I am using. 

Config for the card and forecast output attached below.

**Screenshots**

![image](https://github.com/mlamberts78/weather-chart-card/assets/10956987/21e62e36-0d74-4b61-8fbd-9c8fd41cba62)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: 2.4.3
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE: 2024.3.3 on HAOS
 - OS: WIndows 11
 - Browser edge 122 and firefox 124
 
**Additional context**
Weather.com HACS integration for weather. Card sitting inside a conditional card

** Card config**
```yaml
type: conditional
conditions:
  - condition: state
    entity: input_select.wu_source
    state: other
card:
  type: custom:stack-in-card
  mode: vertical
  cards:
    - type: custom:mushroom-title-card
      title: Prognoza {{states('sensor.wu_other_location')}}
    - type: custom:weather-chart-card
      entity: weather.wu_other
      show_time: false
      show_date: true
      forecast:
        show_probability: true
        type: daily
        style: style2
        round_temp: false
        use_12hour_format: false
      units:
        pressure: ''
        speed: ''
      show_current_condition: true
      show_temperature: true
      animated_icons: true
      icon_style: style1
      show_main: true
      show_attributes: false
      icons_size: '50'
      current_temp_size: '20'
```
**Weather.com forecast output for the first couple of days**
```yaml
weather.wu_other:
  forecast:
    - cloud_coverage: 48
      condition: cloudy
      precipitation: 0
      precipitation_probability: 2
      temperature: 15
      templow: 7
      datetime: "2024-03-29T06:00:00Z"
      uv_index: 3
      wind_bearing: SSW
      wind_speed: 25
      humidity: 60
    - cloud_coverage: 43
      condition: partlycloudy
      precipitation: 0
      precipitation_probability: 7
      temperature: 20
      templow: 11
      datetime: "2024-03-30T06:00:00Z"
      uv_index: 3
      wind_bearing: SE
      wind_speed: 13
      humidity: 71
```
