### ISSUE TITLE
After 2024.4.0 update entity not found for forecast

### ISSUE THREAD

**Issue by bvdkerkhof** [mlamberts78/weather-chart-card#157]
**Describe the bug**
After upgrading to HA 2024.4.0 the card stopped working, it tells me to check the entity.

**To Reproduce**
1. just open the card

**Expected behavior**
Expected to show the information

**Desktop (please complete the following information):**
 - Version 2.4.5
 - 2024.4.0
 - OS: Venv with python 3.12.4
 - All browsers

**Additional context**
Guess this is due the removal of the "forecast" in the weather entity. So the forecasts are not as an attribute shown anymore.

**Comment by mlamberts78** [comment]
Please provide more information.
Which weather integration are you using?
Provide the output of the forecast data (developer tools - services - get forecasts)

**Comment by Loman0815** [comment]
I do have the same problem since updating to 2024.4.0. I tried it with weather.home and weather.openweathermap.

Here an example of the weather.home output:

```
weather.home:
  forecast:
    - condition: partlycloudy
      datetime: "2024-04-05T10:00:00+00:00"
      wind_bearing: 279.8
      temperature: 20.9
      templow: 6.1
      wind_speed: 17.6
      precipitation: 0
      humidity: 71
    - condition: partlycloudy
      datetime: "2024-04-06T10:00:00+00:00"
      wind_bearing: 356.2
      temperature: 23.7
      templow: 6.4
      wind_speed: 9
      precipitation: 0
      humidity: 61
    - condition: partlycloudy
      datetime: "2024-04-07T10:00:00+00:00"
      wind_bearing: 239.2
      temperature: 22.4
      templow: 7.6
      wind_speed: 7.2
      precipitation: 0
      humidity: 65
    - condition: partlycloudy
      datetime: "2024-04-08T10:00:00+00:00"
      wind_bearing: 85.1
      temperature: 22.2
      templow: 8.4
      wind_speed: 6.1
      precipitation: 0
      humidity: 55
    - condition: rainy
      datetime: "2024-04-09T10:00:00+00:00"
      wind_bearing: 234.8
      temperature: 18.5
      templow: 8.2
      wind_speed: 19.1
      precipitation: 4.4
      humidity: 57
    - condition: cloudy
      datetime: "2024-04-10T10:00:00+00:00"
      wind_bearing: 237.7
      temperature: 9.1
      templow: 7.4
      wind_speed: 11.2
      precipitation: 4.1
      humidity: 78
```
