### ISSUE TITLE
Error in Home Assistant log about "Polymer module code"

### ISSUE THREAD

**Issue by bigcookie** [mlamberts78/weather-chart-card#200]
**Describe the bug**
I am using the weather card, but from time to time the following error appears in the logfile:

Logger: frontend.js.latest.202406101
Quelle: components/system_log/__init__.py:333
Erstmals aufgetreten: 14:37:03 (5 Vorkommnisse)
Zuletzt protokolliert: 15:52:33

Uncaught error from Safari 17.5 on Mac OS 10.15.7 ReferenceError: Can't find variable: Polymer module code (/hacsfiles/lovelace-weather-card-chart/weather-card-chart.js:100:39)

**To Reproduce**
I simply set up the weather card with a tomorrow.io weather component. Card was installed via HACS

**Expected behavior**
Error should not occur :-)

**Screenshots**
![Screenshot 2024-06-25 at 16 04 15](https://github.com/mlamberts78/weather-chart-card/assets/2866102/f508c32d-a590-45c8-872c-c16ad093b9ec)
![Screenshot 2024-06-25 at 16 04 29](https://github.com/mlamberts78/weather-chart-card/assets/2866102/90b32829-3687-4c95-baad-5e113ef8d8a6)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: v2.4.7
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2023.07.3): Docker, 2024.6.3
 - OS: [e.g. 10.3, venv, etc.]: MacOS Sonoma 14.5
 - Browser [e.g. chrome, safari]: Safari 
 - Version [e.g. 22]: Version 17.5 (19618.2.12.11.6)

**Additional context**
Yaml code for card setup:
```
cards:
  - type: custom:weather-chart-card
    entity: weather.tomorrow_io_home_hourly
    show_main: true
    show_temperature: true
    show_current_condition: false
    show_attributes: true
    show_time: false
    show_time_seconds: false
    show_day: false
    show_date: false
    show_humidity: true
    show_pressure: true
    show_wind_direction: true
    show_wind_speed: true
    show_sun: true
    show_feels_like: false
    show_dew_point: false
    show_wind_gust_speed: false
    show_visibility: false
    show_last_changed: false
    use_12hour_format: false
    icons_size: '40'
    animated_icons: true
    icon_style: style2
    autoscroll: false
    forecast:
      precipitation_type: rainfall
      show_probability: true
      labels_font_size: '11'
      precip_bar_size: '70'
      style: style2
      show_wind_forecast: true
      condition_icons: true
      round_temp: false
      type: daily
      number_of_forecasts: '5'
      disable_animation: false
    units:
      pressure: ''
      speed: km/h
    current_temp_size: '36'
  - type: custom:weather-chart-card
    entity: weather.tomorrow_io_home_hourly
    show_main: false
    show_temperature: true
    show_current_condition: true
    show_attributes: false
    show_time: false
    show_time_seconds: false
    show_day: false
    show_date: false
    show_humidity: true
    show_pressure: true
    show_wind_direction: true
    show_wind_speed: true
    show_sun: true
    show_feels_like: false
    show_dew_point: false
    show_wind_gust_speed: false
    show_visibility: false
    show_last_changed: false
    use_12hour_format: false
    icons_size: '40'
    animated_icons: true
    icon_style: style2
    autoscroll: false
    forecast:
      precipitation_type: rainfall
      show_probability: true
      labels_font_size: '11'
      precip_bar_size: '700'
      style: style2
      show_wind_forecast: true
      condition_icons: true
      round_temp: false
      type: hourly
      number_of_forecasts: '8'
      disable_animation: false
    units:
      pressure: ''
      speed: km/h
    current_temp_size: '36'
type: vertical-stack
```

And another weather chart card on another tab:
```
cards:
  - type: custom:weather-chart-card
    entity: weather.tomorrow_io_home_hourly
    show_main: true
    show_temperature: true
    show_current_condition: true
    show_attributes: false
    show_time: false
    show_time_seconds: false
    show_day: false
    show_date: false
    show_humidity: false
    show_pressure: false
    show_wind_direction: false
    show_wind_speed: false
    show_sun: false
    show_feels_like: false
    show_dew_point: false
    show_wind_gust_speed: false
    show_visibility: false
    show_last_changed: false
    use_12hour_format: false
    icons_size: '40'
    animated_icons: false
    icon_style: style2
    autoscroll: false
    forecast:
      precipitation_type: rainfall
      show_probability: true
      labels_font_size: '11'
      precip_bar_size: '100'
      style: style2
      show_wind_forecast: false
      condition_icons: true
      round_temp: false
      type: hourly
      number_of_forecasts: '10'
      disable_animation: false
    units:
      pressure: ''
      speed: km/h
    current_temp_size: '36'
  - entities:
      - entity: sensor.wetter_heute_berlin_kurz
        name: 'Heute:'
        icon: mdi:weather-partly-snowy-rainy
    type: entities
    show_header_toggle: false
  - type: sensor
    entity: sensor.mainsupply_power
    name: Aktueller Stromverbrauch
    detail: 1
type: vertical-stack
```
