### ISSUE TITLE
Rendering on iPad compainon app broken

### ISSUE THREAD

**Issue by tomlut** [mlamberts78/weather-chart-card#228]
**Describe the bug**
This card displays correctly on my descktop (firefox) and iPhone. However it does not render correctly on my iPad Pro 12.9" using the official HA companion app. It **does** display correctly on the iPad in Safari. 

**To Reproduce**
1. Create card
2. View it in HA companion app on iPad pro

**Expected behavior**
Correct rendering in all browsers. 

**Screenshots**
iPhone:

![23136](https://github.com/user-attachments/assets/d00fa405-300b-4153-b948-b3b9bcaf87c4)

iPad:

![IMG_0936](https://github.com/user-attachments/assets/3b3e8e77-4e38-41d6-9090-eeafdf53e581)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 2.4.7
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE 2024.8.2 HA OS x86 Generic
 - OS: 10.3
 - Browser HA companion app
 - Version 2024.730

**Additional context**
Card config:
```
type: custom:weather-chart-card
entity: weather.hobart
show_main: false
show_attributes: false
forecast:
  condition_icons: false
  show_wind_forecast: false
  precipitation_type: ''
  style: style2
  type: daily
units:
  pressure: ''
  speed: ''
title: Weather
animated_icons: false
show_pressure: false
show_humidity: false
show_wind_direction: false
show_wind_speed: false
use_12hour_format: false
icon_style: style2
icons_size: '30'
show_temperature: false
show_current_condition: false
autoscroll: false
show_time: false
show_last_changed: false
```
