### ISSUE TITLE
Canvas view disappears when used in bubble card popup

### ISSUE THREAD

**Issue by perok** [mlamberts78/weather-chart-card#238]
**Describe the bug**

I have added this card inside the [bubble card popup](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#pop-up). Things are showing nicely the first time the popup is opened. After closing and opening again then the canvas view for the bar chart is gone.

**To Reproduce**
1. Create bubble card popup containing the weather chart card

```yaml
# Button
              - type: custom:bubble-card
                card_type: name
                name: "Weather"
                button_action:
                  tap_action:
                    action: navigate
                    navigation_path: "#weather"
# Popup

          - type: vertical-stack
            cards:
              - type: custom:bubble-card
                card_type: pop-up
                hash: "#weather"

              - type: custom:weather-chart-card
                entity: weather.home
                forecast:
                  style: style2
                  precipitation_type: ""
                  type: daily
                  disable_animation: true
                animated_icons: true
                icon_style: style2
                show_time: false
                show_temperature: true
                show_main: false
                units:
                  pressure: ""
                  speed: ""
```

2. Open the popup 
3. Close the popup
4. Open the popup 

**Expected behavior**

The bar chart showing every time one opens the popup.

**Screenshots**

Everything is showing as it should:
![image](https://github.com/user-attachments/assets/baabae57-d89d-4e3f-8057-e3086ee2b5a8)
After reopening we are seeing this:
![image](https://github.com/user-attachments/assets/9f63530c-f107-4490-8482-918960396abf)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: 2.4.9
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE: 2024.8.3
 - OS: NixOS, Android
 - Browser: Reproduces in Android HA app, firefox, chrome

**Additional context**
