### ISSUE TITLE
Alternate windspeed doesn't seem to work

### ISSUE THREAD

**Issue by Nickduino** [mlamberts78/weather-chart-card#255]
Here's what I'd like to do: display the forecasts from my local weather forecast (Météo France) and the wind from AccuWeather:

![image](https://github.com/user-attachments/assets/844b7c07-7e4d-46d5-a4f4-e0ce00afb021)

But it doesn't work:

![image](https://github.com/user-attachments/assets/f19bbcb3-d8fc-425d-bd61-40085ea77a78)

Météo France's code:
```
type: custom:weather-chart-card
entity: weather.clermont_ferrand
title: Météo France
show_main: true
show_temperature: true
show_current_condition: true
show_attributes: false
icons_size: 35
animated_icons: true
icon_style: style1
autoscroll: false
forecast:
  precipitation_type: rainfall
  show_probability: false
  labels_font_size: "12"
  precip_bar_size: "100"
  style: style2
  show_wind_forecast: true
  condition_icons: true
  round_temp: false
  type: daily
  number_of_forecasts: "7"
  disable_animation: false
locale: fr
```

AccuWeather's code:
```
type: custom:weather-chart-card
entity: weather.accuweather_clermont
title: AccuWeather
show_main: true
show_temperature: true
show_current_condition: true
show_attributes: false
icons_size: 35
animated_icons: true
icon_style: style1
autoscroll: false
forecast:
  precipitation_type: rainfall
  show_probability: false
  labels_font_size: "12"
  precip_bar_size: "100"
  style: style2
  show_wind_forecast: true
  condition_icons: true
  round_temp: false
  type: daily
  number_of_forecasts: "7"
  disable_animation: false
locale: fr
```

The hybrid's code:
```
type: custom:weather-chart-card
entity: weather.clermont_ferrand
title: Hybrid
show_main: true
show_temperature: true
show_current_condition: true
show_attributes: false
icons_size: 35
animated_icons: true
icon_style: style1
autoscroll: false
forecast:
  precipitation_type: rainfall
  show_probability: false
  labels_font_size: "12"
  precip_bar_size: "100"
  style: style2
  show_wind_forecast: true
  condition_icons: true
  round_temp: false
  type: daily
  number_of_forecasts: "7"
  disable_animation: false
locale: fr
winddir: weather.accuweather_clermont
windspeed: weather.accuweather_clermont
```

**Or did I misunderstood the functionality and it works only for current values rather than forecasts?** In that case, how can I achieve the result I want?

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION : V2.4.11
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2023.07.3) 2024.10
 - OS: Windows 10
 - Browser Chrome
