### ISSUE TITLE
support of the HA built in "Visibility" feature

### ISSUE THREAD

**Issue by ChristophCaina** [mlamberts78/weather-chart-card#280]
**Is your feature request related to a problem? Please describe.**
I am using the card in a Dashboard based on the "new" Sections Layout - and want to create a functionallity, that will make use of the new "visibility" feature which is available for some time now - to show or hide cards under certain conditions.

Unfortunately, as soon as I use this visibility option on the weather-chart-card, the whole section where the card will be placed will disappear from the dashboard.
it is only visible in the RAW editor of the Dashboard - and I have to remove the visibility options from there, to restore the dashboard.

**Describe the solution you'd like**
make use of the available features provided by HomeAssistant

The yaml for this feature is:
```
        visibility:
          - condition: state
            entity: input_boolean.toggle_card_weather
            state: "on"
```

**Additional context**

Yaml Code that fails:

```
type: sections
max_columns: 4
title: test
path: test
icon: mdi:test-tube
sections:
  - type: grid
    cards:
      - type: heading
        heading: Wetter
        heading_style: title
        badges:
          - type: entity
            show_state: true
            show_icon: true
            entity: input_boolean.toggle_card_weather
            color: state
            tap_action:
              action: toggle
          - show_state: true
            show_icon: true
            entity: weather.renningen
        icon: mdi:weather-partly-cloudy
      - type: custom:weather-chart-card
        entity: weather.XYZ
        show_main: true
        show_temperature: true
        show_current_condition: true
        show_attributes: true
        show_time: true
        show_time_seconds: true
        show_day: true
        show_date: true
        show_humidity: true
        show_pressure: true
        show_wind_direction: true
        show_wind_speed: true
        show_sun: true
        show_feels_like: false
        show_dew_point: false
        show_wind_gust_speed: true
        show_visibility: false
        show_last_changed: true
        use_12hour_format: false
        icons_size: 25
        animated_icons: false
        icon_style: style1
        forecast:
          precipitation_type: rainfall
          show_probability: true
          labels_font_size: "11"
          precip_bar_size: "100"
          style: style2
          show_wind_forecast: true
          condition_icons: true
          round_temp: false
          type: daily
          number_of_forecasts: "0"
          disable_animation: true
        units:
          pressure: ""
          speed: ""
        title: ""
        visibility:
          - condition: state
            entity: input_boolean.toggle_card_weather
            state: "on"
      - type: custom:weather-chart-card
        entity: weather.XYZ
        show_main: false
        show_temperature: true
        show_current_condition: true
        show_attributes: true
        show_time: false
        show_time_seconds: false
        show_day: false
        show_date: false
        show_humidity: true
        show_pressure: true
        show_wind_direction: true
        show_wind_speed: true
        show_sun: false
        show_feels_like: false
        show_dew_point: true
        show_wind_gust_speed: true
        show_visibility: false
        show_last_changed: true
        use_12hour_format: false
        icons_size: 25
        animated_icons: false
        icon_style: style1
        forecast:
          precipitation_type: probability
          show_probability: false
          labels_font_size: "11"
          precip_bar_size: "100"
          style: style2
          show_wind_forecast: true
          condition_icons: true
          round_temp: false
          type: hourly
          number_of_forecasts: "0"
          disable_animation: false
        units:
          pressure: ""
          speed: ""
        feels_like: sensor.gw2000a_feels_like_temperature
        uv: sensor.gw2000a_uv_index
        dew_point: sensor.gw2000a_dewpoint
        wind_gust_speed: sensor.gw2000a_wind_gust
        windspeed: sensor.gw2000a_wind_speed
        winddir: sensor.gw2000a_wind_direction
        humid: sensor.gw2000a_humidity
        press: sensor.gw2000a_absolute_pressure
        temp: sensor.gw2000a_outdoor_temperature
        title: Current
    column_span: 2
cards: []
```

Dashboard without using the visibility feature:
![image](https://github.com/user-attachments/assets/22ba4505-54f6-439a-bdb8-c06598513a60)

Dashboard with using the visibility feature:
![image](https://github.com/user-attachments/assets/e9280e2a-e9a9-4340-95f0-3a91753657a1)
