### ISSUE TITLE
visibility option

### ISSUE THREAD

**Issue by Miami-66** [mlamberts78/weather-chart-card#290]
**Describe the bug**
When I add the option visibility for the weather-chart-card, the dashboard is shown as an empty page. 
When I delete the visibility opton in YAML the dashboard (and the weather-chart-card) is shown again.

When I just select in the visual editor in the visibility tab any condition type, I see after 1 to 15s seconds "Cannot read properties of undefined (reading 'state')" instead of the preview. 

This code for the view works  fine:
```
type: masonry
path: test
title: Test
cards:
  - type: custom:weather-chart-card
    entity: weather.openweathermap
    units:
      speed: ""
```

This does not work (shows an empty page):
```
type: masonry
path: test
title: Test
cards:
  - type: custom:weather-chart-card
    entity: weather.openweathermap
    units:
      speed: ""
    visibility:
      - condition: state
        entity: input_boolean.anzeige_wetter
        state: "on"
```
**Screenshot**
![Image](https://github.com/user-attachments/assets/aa4f65cf-4fc3-479a-84f3-2f89b7d2b2a1)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: V2.4.11
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE: 2025.02.01
 - OS: HA OS 14.2
 - Browser: MS Edge V133.0.3065.82  and Google Chrome V133.0.6943.127

**Additional context**
There is no difference if I use a GRID or a TILE Layout.
