### ISSUE TITLE
Date and time now shown

### ISSUE THREAD

**Issue by poudenes** [mlamberts78/weather-chart-card#66]
**Describe the bug**
Date and time now shown 

**yaml code**
```
type: custom:weather-chart-card
entity: weather.accu_weather
show_time: true
show_date: true
show_day: true
animated_icons: true
forecast:
  show_wind_forecast: true
  condition_icons: true
  style: style2
units:
  speed: km/h
  pressure: hPa
```

**Screenshots**
<img width="503" alt="Screenshot 2024-02-05 at 15 26 43" src="https://github.com/mlamberts78/weather-chart-card/assets/4399532/93c2a26a-ac63-431e-bca6-854e18a50db1">

**Desktop (please complete the following information):**
Weather Card version: V2.2.5
Core: 2024.1.6
Supervisor: 2023.12.1
Operating System: 11.4
Frontend: 20240104.0

Viewed on iMac MacOS 14.2.1:

- Safari: 17.2.1 (19617.1.17.11.12)
- Chrome: 119.0.6045.123 (Official Build) (arm64)

**Additional context**
Cleared cache of Safari and Chrome did not help.
