### ISSUE TITLE
Add the tap_action option

### ISSUE THREAD

**Issue by OCT0PUSCRIME** [mlamberts78/weather-chart-card#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Some Lovelace cards have the option of having a tap_action specified. I use browser mod popups to display additional cards when I want more information on something. Tap action would be nice on this card so I can pull up a radar view iwith a dofferent custom card if desired desired.

Additionally, I can see there isn't really anywhere to tap on this card except the weather icons on the forecast section, which pulls open the weather entity. It would be nice if the tap action can also be called from elsewhere on the card, maybe near the main weather icon for the current weather.

**Additional context**

Example of YAML I am trying to implement (relies on HACS weather radar card):

```
type: custom:weather-chart-card
entity: weather.home
show_main: true
show_current_condition: true
show_attributes: false
show_time: false
show_day: false
show_date: false
show_humidity: false
show_pressure: false
show_wind_direction: false
show_wind_speed: false
show_sun: false
show_feels_like: true
icons_size: 25
animated_icons: true
icon_style: style1
forecast:
  precipitation_type: rainfall
  labels_font_size: '11'
  precip_bar_size: '100'
  style: style2
  show_wind_forecast: true
  condition_icons: true
  round_temp: false
  type: daily
  use_12hour_format: false
units:
  pressure: ''
  speed: ''
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Radar
      content:
        type: custom:weather-radar-card
        show_scale: false
        show_marker: true
        static_map: false
        show_zoom: false
        show_playback: false
        show_range: false
        square_map: false
        show_recenter: true
        extra_labels: true
        map_style: Voyager
        data_source: RainViewer-DarkSky
```
