### ISSUE TITLE
Hourly Forecast not being displayed correctly in different views

### ISSUE THREAD

**Issue by kaizersoje** [mlamberts78/weather-chart-card#93]
**Describe the bug**
I have got the same card in different dashboards but they are being displayed differently. The only difference with the 2 views is that the one where the card is not being displayed correctly is in a column with a defined width, 

**To Reproduce**

**Expected behavior**
Expect the card to be displayed the same

![image](https://github.com/mlamberts78/weather-chart-card/assets/54566217/54a53aa8-4116-4996-86d3-ff2bafe70e96)
![image](https://github.com/mlamberts78/weather-chart-card/assets/54566217/487ab2d7-eca2-4c6d-8ffd-f9e3284aedbb)

**Screenshots**

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 2.2.8
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2023.07.3) 2024.2.0
 - OS: [e.g. 10.3, venv, etc.] 11.5
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 121.0.6167.161

**Additional context**
I have pasted the code below
```yaml
type: custom:weather-chart-card
entity: weather.home_hourly
forecast:
  labels_font_size: 12.5
  show_wind_forecast: true
  precipitation_type: rainfall
  type: hourly
  style: style2
  round_temp: true
  precip_bar_size: '100'
  chart_text_color: black
show_main: true
show_attributes: false
show_current_condition: true
icons: /local/icons/weather_icons/animated/
show_temperature: false
show_time: false
animated_icons: true
icon_style: style2
units:
  pressure: ''
  speed: ''
```

**Comment by mlamberts78** [comment]
I’m not able to reproduce this, please give me some more information.

**Comment by kaizersoje** [comment]
The card is placed under a `layout-card` and this is how the card looks like.

```yaml
type: custom:layout-card
layout: horizontal
min_columns: 3
column_width: [33%, 34%, 33%]
cards:
  - type: custom:weather-chart-card
    entity: weather.laverton_hourly
    forecast:
      labels_font_size: 12.5
      show_wind_forecast: true
      precipitation_type: rainfall
      type: hourly
      style: style2
      round_temp: true
      precip_bar_size: '100'
      chart_text_color: black
    show_main: true
    show_attributes: false
    show_current_condition: true
    icons: /local/icons/weather_icons/animated/
    show_temperature: false
    show_time: false
    animated_icons: true
    icon_style: style2
    units:
      pressure: ''
      speed: ''
```
![image](https://github.com/mlamberts78/weather-chart-card/assets/54566217/79ba939c-29f3-4993-b826-e218748e9174)
